"""empty message

Revision ID: 0263479dbedf
Revises: ffdc0a98111c
Create Date: 2021-03-02 13:33:51.325586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0263479dbedf'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('rarity', sa.String(length=100), nullable=True),
    sa.Column('photoUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('uploadDate', sa.Date(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('ownerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stickers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sticker_id'], ['stickers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sticker_id')
    )
    op.create_table('post_stickers',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('sticker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['sticker_id'], ['stickers.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'sticker_id')
    )
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('photoUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photoUrl')
    op.drop_column('users', 'bio')
    op.drop_table('post_stickers')
    op.drop_table('user_stickers')
    op.drop_table('posts')
    op.drop_table('stickers')
    # ### end Alembic commands ###
