"""empty message

Revision ID: a27d7dd97792
Revises: 0263479dbedf
Create Date: 2021-03-03 09:13:09.655045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27d7dd97792'
down_revision = '0263479dbedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('photoUrl', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'photoUrl')
    # ### end Alembic commands ###
