"""empty message

Revision ID: 764603c693bb
Revises: 9e337ffa1e72
Create Date: 2021-03-14 20:51:29.849659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764603c693bb'
down_revision = '9e337ffa1e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'message',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
