"""empty message

Revision ID: 9e337ffa1e72
Revises: ef542ca8b422
Create Date: 2021-03-08 10:39:42.300220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e337ffa1e72'
down_revision = 'ef542ca8b422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_stickers_post_id_fkey', 'post_stickers', type_='foreignkey')
    op.drop_constraint('post_stickers_sticker_id_fkey', 'post_stickers', type_='foreignkey')
    op.create_foreign_key(None, 'post_stickers', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_stickers', 'stickers', ['sticker_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_stickers', type_='foreignkey')
    op.drop_constraint(None, 'post_stickers', type_='foreignkey')
    op.create_foreign_key('post_stickers_sticker_id_fkey', 'post_stickers', 'stickers', ['sticker_id'], ['id'])
    op.create_foreign_key('post_stickers_post_id_fkey', 'post_stickers', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
